version: 2
jobs:
  test-vpn:
    machine: true
    steps:
    - run:
        name: Install OpenVPN
        command: sudo apt-get update -y && sudo apt-get install openvpn
        
    - run:
        name: Init VPN
        command: |
          echo "$VPN_CONFIG" > raw.txt
          cat raw.txt | tr " " "\n" | base64 --decode >> config.ovpn \nprintf \"$VPN_USER\\n$VPN_PASSWORD\\n\" >> vpn.login\n
    - run:
        name: Connect to VPN
        command: |
          sudo openvpn --config config.ovpn --auth-user-pass vpn.login > openvpn.log 2>&1 &
          #sudo /bin/bash -c 'echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf'
          while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            sleep 0.1;
          done
    - run:
        name: Do stuff in our infrastructure
        command: echo "Public IP is $(curl -s 'https://ipecho.net/plain')"
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
