version: 2.1
jobs: 
  test-vpn:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - checkout
      - run:
          name: Install Redsocks
          command: |
            sudo apt-get update -y && sudo apt install redsocks
            
      - add_ssh_keys:
          fingerprints:
            - "29:a6:37:58:fd:c2:c9:1a:55:b1:5f:65:03:f1:06:ef"
        
      - run:
          name: Run redscocks
          background: true
          command: |
            sudo chmod +x ./iptables-redsocks.sh 
            sudo ./iptables-redsocks.sh start
            
      - run:
          name: Are files here?
          command: |
            pwd
            ls -al

            
      - store_artifacts:
          path: /home/circleci/project/redsocks.log
          destination: redsocks.log
                                                                     
      - run:
          name: Do stuff in our infrastructure
          command: |
            curl ifconfig.me
             
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
