version: 2.1
jobs:
  test-root:
    machine:
      image: ubuntu-1604:202004-01
      # image: ubuntu-1604:201903-01

    
    steps:
    - run:
        name: Install OpenVPN 2.4
        command: |
          sudo sh -c "curl -s https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add -"
          sudo sh -c 'echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list'
          sudo apt-get -q -y update
          sudo apt-get -q -y install openvpn
          sudo openvpn --version
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-root
