version: 2
jobs:
  test-vpn:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "29:a6:37:58:fd:c2:c9:1a:55:b1:5f:65:03:f1:06:ef"    
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update -y && sudo apt-get install openvpn
            sudo apt-get install network-manager-openvpn -y
            #sudo apt-get upgrade openvpn
            #sudo openvpn --version
        
      - run:
          name: Init le VPN
          command: |
            #echo "$VPN_CONFIG" > raw.txt
            #cat raw.txt | tr " " "\n" | base64 --decode >> config.ovpn
            echo $VPN_CONFIG | base64 --decode >> config.ovpn
            #printf "\"$VPN_USER\\n$VPN_PASSWORD\\n\"" >> vpn.login
            #printf "$VPN_USERNAME\n$VPN_PASSWORD\n" >> vpn.login
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            
     # - run:
     #     name: Setup VPN tunnel
     #     command: |
     #       sudo /sbin/modprobe tun
     #       cd /dev
     #       sudo MAKEDEV tun
     #       sudo openvpn --mktun --dev tun0
     #       sudo ip link set dev tun0 up
     #       sudo ip addr show
            
      - run:
          name: Connect to VPN
          background: true
          command: |
            echo "Connecting VPN client..."
            #sudo sysctl net.ipv4.ip_forward=1
            #sudo openvpn --config config.ovpn --daemon
            sudo openvpn --config config.ovpn > openvpn.log 2>&1 &
            #sudo openvpn --config config.ovpn 2>&1 &
            #sudo openvpn --config config.ovpn --auth-user-pass vpn.login > openvpn.log 2>&1 &
            #sudo openvpn --config config.ovpn --auth-user-pass vpn.login 2>&1 &
            #sudo /bin/bash -c 'echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf'
            #while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            # sleep 2;
            #done

            #echo "VPN client connected"
            #echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            #route -n
            #ifconfig -a
            
               
      - run:
          name: Do stuff in our infrastructure
          command: |
            route -n
            ifconfig -a
            sleep 10
            #sudo sh -c 'ip route add 0.0.0.0/1 via 172.31.128.1' 
            #while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            #  sleep 1;
            #done
            while [ $(ip route show default|grep -c "tun0") == 0 ]; do
              sleep 5
              echo "Still attempting to connect VPN client...";
            done
            route -n
            ifconfig -a            
            echo "VPN client connected"
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            
            #Ping VPN server private IP
            ping -c 5 172.31.40.6
            
      - run:
              name: Disconnect from OpenVPN
              command: sudo killall openvpn || true
              when: always
            
      - store_artifacts:
          path: /home/circleci/project/openvpn.log
          destination: openvpn.log

            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
