version: 2.1
jobs:
  test-vpn:
    machine:
      image: ubuntu-1604:202004-01
    
    steps:
    - run:
        name: Install OpenVPN
        command: |
          sudo su
          whoami
          #sudo su && curl -s https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add - && echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
          apt-get update
          #apt install -y openvpn
          #openvpn --version
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
