version: 2
jobs:
  test-vpn:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "29:a6:37:58:fd:c2:c9:1a:55:b1:5f:65:03:f1:06:ef"    
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update -y && sudo apt-get install openvpn
        
      - run:
          name: Init le VPN
          command: |
            #echo "$VPN_CONFIG" > raw.txt
            #cat raw.txt | tr " " "\n" | base64 --decode >> config.ovpn
            echo $VPN_CONFIG | base64 --decode >> config.ovpn
            #printf "\"$VPN_USER\\n$VPN_PASSWORD\\n\"" >> vpn.login
            #printf "$VPN_USERNAME\n$VPN_PASSWORD\n" >> vpn.login
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            
      - run:
          name: Connect to VPN
          #background: true
          command: |
            echo "Connecting VPN client..."
            sudo openvpn --config config.ovpn --daemon
            
            while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
             sleep 1;
            done
            
            echo "VPN client connected"

            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            route -n
            ifconfig -a
                        
            #Ping VPN server private IP
            ping -c 3 172.31.40.6
            
      #- store_artifacts:
      #    path: /home/circleci/project/openvpn.log
      #    destination: openvpn.log
          
      - run:
          name: Do stuff in our infrastructure
          command: |
            #while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            #  sleep 1;
            #done
            route -n
            ifconfig -a            
            #echo "VPN client connected"
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            
            #Ping VPN server private IP
            #ping -c 3 172.31.40.6

            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
