version: 2
jobs:
  commit-stuff:
    docker:
      - image: circleci/python:latest
    
    steps:
      - checkout
      - run:
          name: Get commit message
          command: |
            COMMIT_MESSAGE=$(git log --format="%s" -n 1 $CIRCLE_SHA1)
            echo $COMMIT_MESSAGE
            COMMIT_AUTHOR=$(git log --format="%an" -n 1 $CIRCLE_SHA1)
            echo $COMMIT_AUTHOR
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - commit-stuff
