version: 2
jobs:
  test-vpn:
    docker:
      - image: circleci/python:3.7
    working_directory: /home/circleci
    
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "29:a6:37:58:fd:c2:c9:1a:55:b1:5f:65:03:f1:06:ef"
      - run:
          name: Check presence of .ssh folder
          command: pwd
    #  - run:
    #      name: SSH into remote
    #      command: ssh openvpnas@ec2-18-202-221-47.eu-west-1.compute.amazonaws.com \ pwd
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
