version: 2
jobs:
  commit-stuff:
    docker:
      - image: circleci/python:latest
    
    steps:
      - run:
          name: Get commit message
          command: |
            COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"
            echo $COMMIT_MESSAGE
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - commit-stuff
