version: 2
jobs:
  test-vpn:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "29:a6:37:58:fd:c2:c9:1a:55:b1:5f:65:03:f1:06:ef"    
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update -y && sudo apt-get install openvpn
            sudo apt-get install network-manager-openvpn -y
            #sudo apt-get upgrade openvpn
            #sudo openvpn --version
        
      - run:
          name: Init le VPN
          command: |
            echo $VPN_CONFIG | base64 --decode >> config.ovpn
            #printf "\"$VPN_USER\\n$VPN_PASSWORD\\n\"" >> vpn.login
            #printf "$VPN_USERNAME\n$VPN_PASSWORD\n" >> vpn.login
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            

      - run:
          name: Connect to VPN
          #background: true
          command: |
            echo "Connecting VPN client..."
            #sudo openvpn --config config.ovpn > openvpn.log 2>&1 &
            sudo openvpn --config config.ovpn --daemon > openvpn.log 2>&1
            #sudo openvpn --config config.ovpn --auth-user-pass vpn.login > openvpn.log 2>&1 &
            #sudo openvpn --config config.ovpn --auth-user-pass vpn.login 2>&1 &
            sudo sh -c 'echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf'
            while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
             sleep 0.1;
            done    
            echo "VPN client connected"
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)" > currentIP.txt
            ip route show default >> currentIP.txt
            route -n >> currentIP.txt
            ifconfig -a >> currentIP.txt
            ping -c 5 172.31.40.6
            
      - store_artifacts:
          path: /home/circleci/project/openvpn.log
          destination: openvpn.log
          
      - store_artifacts:
          path: /home/circleci/project/currentIP.txt
          destination: currentIP.txt
          
      - run:
          name: Do stuff in our infrastructure
          command: |
            route -n
            ifconfig -a
            #while [ $(ip route show default|grep "0.0.0.0"|grep -c "tun0") == 0 ]; do
            #  sleep 1;
            #done
            #echo "VPN client connected"
            echo "Public IP is $(wget -qO- http://checkip.amazonaws.com | tee initial.ip)"
            
      - run:
              name: Disconnect from OpenVPN
              command: sudo killall openvpn || true
              when: always
            
workflows:
  version: 2
  build-and-release:
    jobs:
    - test-vpn
